from dao.orm.model import *

db.create_all()


Dima = Student(student_id=1,
                 student_username = 'DmitriyKoltsov',
                 student_name = 'Dmitriy',
                 student_lastname = 'Koltsov',
                 student_birthday =  '01.01.1999',
                 student_group = 'КМ-63',


                 student_grades = 98,
                 student_proglanguage = 'python',
                 student_specialization = 113)

 Anna = Student(student_id=2,
                 student_username = 'AnnaTrishyna',
                 student_name = 'Anna',
                 student_lastname = 'Trishyna',
                 student_birthday =  '17.12.1998',
                 student_group = 'КМ-63',


                 student_grades = 80,
                 student_proglanguage = 'python',
                 student_specialization = 113)


 Vlad = Student(student_id=3,
                 student_username = 'VladKanevskiy',
                 student_name = 'Vlad',
                 student_lastname = 'Kanevskiy',
                 student_birthday =  '04.02.1999',
                 student_group = 'КМ-63',


                 student_grades = 98,
                 student_proglanguage = 'python',
                 student_specialization = 113)
# ------------------------------------------------------------------------------------------------------
# ------------------------------------------------------------------------------------------------------



Олег = Teacher(teacher_id= 0000000300871028 ,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Юлія = Teacher(teacher_id= '000000033681552X',                               #id!!!!!!!
                 teacher_username = 'BaiJulia',
                 teacher_name = 'Julia',
                 teacher_lastname = 'Bai',
                 teacher_birthday =  '00.00.0000',
                 teacher_position = ' ',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Лілія = Teacher(teacher_id= 0000000157504101,
                 teacher_username = 'LilyVovk',
                 teacher_name = 'Lily',
                 teacher_lastname = 'Vovk',
                 teacher_birthday =  '21.04.1967',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')

Олег = Teacher(teacher_id=1,
                 teacher_username = 'OlegChertov',
                 teacher_name = 'Oleg',
                 teacher_lastname = 'Chertov',
                 teacher_birthday =  '01.01.1999',
                 teacher_position = 'КМ-63',
                 teacher_subject = '',
                 teacher_hobby = '',
                 teacher_proglanguage ='',
                 teacher_item ='',
                 teacher_works ='',
                 teacher_specialization ='')
# ---------------------------------------------------------------------------------------------------------
# ---------------------------------------------------------------------------------------------------------


    diplomItem_id = 1,
    diplomItem_name = db.Column(db.String(1000), nullable=False)
    diplomItem_subject = db.Column(db.String(20), nullable=False)
    diplomItem_proglanguage=db.Column(db.Integer, primary_key=True)
    diplomItem_teacher=db.Column(db.Integer, primary_key=True)

